features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: themes/StephanieCoontz/stephanie/images/title.svg
favicon:
  use_default: 0
  path: 'public://Screen Shot.ico'
  mimetype: image/vnd.microsoft.icon
